---
- name: provision vagrant box
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Set timezone
      ansible.builtin.command: "timedatectl set-timezone Europe/Berlin"

    - name: Install packages
      ansible.builtin.apt:
        name:
          - unzip
          - vim
          - jq
          - nodejs
          - npm
        update_cache: yes

    - name: Remove other motds
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob: "/etc/update-motd.d/??-[!w]*"

    - name: Set message of the day
      ansible.builtin.copy:
        src: ./motd
        dest: /etc/update-motd.d/00-welcome
        owner: root
        group: root
        mode: '0755'

    - name: Check if awscli is already installed
      ansible.builtin.stat:
        path: "/usr/local/bin/aws"
      register: "aws_check"

    - name: Download and extract awscli
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /var/tmp
        remote_src: yes
      when: "not aws_check.stat.exists"

    - name: Install aws-cli
      ansible.builtin.command: "/var/tmp/aws/install"
      when: "not aws_check.stat.exists"

    - name: Add aws command completion
      ansible.builtin.lineinfile:
        path: /home/vagrant/.bashrc
        regexp: '^complete -C /usr/local/bin/aws_completer aws'
        line: 'complete -C /usr/local/bin/aws_completer aws'

    - name: Install aws cdk
      ansible.builtin.command: "npm install -g aws-cdk"
